name: campus_erp
description: CampusERP - Flutter + Supabase reference app
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.5.0
  flutter_riverpod: ^2.0.0
  go_router: ^6.0.0
  intl: ^0.18.0
  dio: ^5.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  url_launcher: ^6.1.7
  file_saver: ^0.2.0
  flutter_svg: ^1.1.0
  flutter_markdown: ^0.6.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  freezed: ^2.3.0
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true